# render.yaml

services:
  - name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /movie/<title>
    disk:
      name: data
      mountPath: /mnt/data
    envVars:
      - key: SECRET_KEY
        fromFile: .env
      - key: DEBUG
        value: "True"
    envVarsFromFiles:
      - .env
    ports:
      - 3000
