# render.yaml

services:
  - name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 4 -b 0.0.0.0:10000
    healthCheckPath: /movie/<title>
    disk:
      name: data
      mountPath: /mnt/data
    envVars:
      - key: SECRET_KEY
        fromFile: .env
      - key: DEBUG
        value: "False"
    envVarsFromFiles:
      - .env
    ports:
      - 10000
